DO
$do$
BEGIN
   IF EXISTS (
   		SELECT 1
		FROM information_schema.columns
		WHERE
			table_name='users' and column_name='telegram_chat_id'
	) THEN

	 INSERT INTO notification_settings (user_id, type, telegram_chat_id, delay, created_at, updated_at)
	 SELECT id, 'all', telegram_chat_id, 86400000000000, now(), now() from users;

      ALTER TABLE users DROP COLUMN telegram_chat_id;
   END IF;
END
$do$
